/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Panel.Seguridad;

import Capa_Entidades.EUsuario;
import Capa_Logica.LUsuario;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class InterFrmCambioContra extends javax.swing.JFrame {
    int conf=4;
    EUsuario objusu=new EUsuario();
    /**
     * Creates new form InterFrmCambioContra
     */
    public InterFrmCambioContra() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/Santander.png")).getImage());
        txtpassactual.requestFocus();
    }
    
    private boolean validar() {
        int count = 0;
        if (txtpassactual.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese Contraseña Actual.");
            txtpassactual.requestFocus();
        } else {
            if (txtpassnuevo.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Ingrese Nueva Contraseña.");
                txtpassnuevo.requestFocus();
            } else {
                if (txtpassnuevo.getText().trim().length() < 6) {
                    JOptionPane.showMessageDialog(this, "Nueva Contraseña debe contener un minimo de 6 caracteres.");
                    txtpassnuevo.requestFocus();
                } else {
                    if (txtconfigpass.getText().trim().length() == 0) {
                        JOptionPane.showMessageDialog(this, "Ingrese Confirmacion de la Nueva Contraseña.");
                        txtconfigpass.requestFocus();
                    } else {
                        if (txtpassnuevo.getText().trim().toString().equals(txtconfigpass.getText().trim().toString())) {
                            count = 1;
                        } else {
                            JOptionPane.showMessageDialog(this, "Confirmacion no coincide con la Nueva Contraseña.");
                        }
                    }
                }
            }
        }
        if (count == 1) {
            return true;
        } else {
            return false;
        }
    }
    
    private boolean login() {
        if (validar()) {
            LUsuario lusu = new LUsuario();
            int existe = 0;
            ArrayList<EUsuario> lstusuario = new ArrayList<>();
            lstusuario = lusu.ListaUsuario();
            for (int i = 0; i < lstusuario.size(); i++) {
                if (lstusuario.get(i).getUsuario().equalsIgnoreCase(txtusu.getText().trim())
                        && lstusuario.get(i).getContra().equalsIgnoreCase(txtpassactual.getText().trim())) {
                    existe = 1;
                    objusu = lstusuario.get(i);
                }
            }
            if (existe == 1) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña actual incorrecta.");
                txtpassactual.requestFocus();
                return false;
            }
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpassnuevo = new javax.swing.JPasswordField();
        txtpassactual = new javax.swing.JPasswordField();
        txtconfigpass = new javax.swing.JPasswordField();
        txtusu = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cambio de Contraseña");

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("Clave Actual");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 132, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel4.setText("Nueva Clave");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 152, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel6.setText("Confirmar Clave");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 172, -1, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 1, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 112, -1, -1));

        txtpassnuevo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel1.add(txtpassnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 172, -1));

        txtpassactual.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtpassactual.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtpassactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 172, -1));

        txtconfigpass.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel1.add(txtconfigpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 172, -1));

        txtusu.setEditable(false);
        txtusu.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtusu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 172, -1));

        btnguardar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnguardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 70, 30));

        btnsalir.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnsalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 70, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChangePassword.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        if(login()){
            LUsuario lu=new LUsuario();
            if (JOptionPane.showConfirmDialog(null, "Se va MODIFICAR su contraseña. ¿Desea Continuar?", "Confirmar", JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_OPTION)) {
                if(lu.CambioContra(objusu.getDNI(), txtpassnuevo.getText().trim().toString())){
                     JOptionPane.showMessageDialog(this, "Se actualizó correctamente su contraseña.");
                     this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Error de tipo de Dato y/o Conexión de BD.");
                }
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterFrmCambioContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterFrmCambioContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterFrmCambioContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterFrmCambioContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterFrmCambioContra().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtconfigpass;
    public javax.swing.JPasswordField txtpassactual;
    public javax.swing.JPasswordField txtpassnuevo;
    public javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
