/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Panel.Seguridad;

import Capa_Entidades.EUsuario;
import Capa_Logica.LUsuario;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXPERTYA
 */
public class InterFrmUsuario extends javax.swing.JInternalFrame {

    int accion = 0;
    ArrayList<EUsuario> lstusuario = new ArrayList<>();
    String titulos[] = {"DNI", "Nombres", "Apellido Paterno", "Apellido Materno", "Usuario",
        "Contraseña", "Estado", "Email", "Libros Electronicos", "Programación Pagos", "Seguridad"};
    DefaultTableModel modTbdatos = new DefaultTableModel(titulos, 0);

    /**
     * Creates new form InterFrmUsuario
     */
    public InterFrmUsuario() {
        initComponents();
        setFrameIcon(new ImageIcon(getClass().getResource("/img/Santander.png")));
        this.setTitle("Mantenimiento de Usuarios");
        tblstusuario.setModel(modTbdatos);
        llenartablausuario();
        chkestado.setSelected(true);
        tblstusuario.getColumnModel().getColumn(5).setMinWidth(0);
        tblstusuario.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(0);
        tblstusuario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblstusuario.getTableHeader().setReorderingAllowed(false);
        txtdni.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
        txtnombres.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
        txtapepat.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
        txtapemat.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
        txtemail.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
        txtcontra.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtapepat = new javax.swing.JTextField();
        chkestado = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtapemat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcontra = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        chklibroselectronico = new javax.swing.JCheckBox();
        chkprogpagos = new javax.swing.JCheckBox();
        chkseguridad = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstusuario = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        lblcont = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnguarda = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANTENIMIENTO DE USUARIOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 730, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel2.setText("DNI");

        txtdni.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtdni.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("Nombres");

        txtnombres.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel4.setText("Apellido Pat.");

        txtapepat.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtapepat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapepatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapepatKeyTyped(evt);
            }
        });

        chkestado.setBackground(new java.awt.Color(255, 255, 255));
        chkestado.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        chkestado.setText("Activo");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel5.setText("Apellido Mat.");

        txtapemat.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtapemat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapematKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapematKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel6.setText("E-mail");

        txtemail.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtemailKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel9.setText("Contraseña");

        txtcontra.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtcontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontraKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel11.setText("Usuario");

        txtusuario.setEditable(false);
        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtusuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });

        chklibroselectronico.setBackground(new java.awt.Color(255, 255, 255));
        chklibroselectronico.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        chklibroselectronico.setText("Libros Electrónicos");

        chkprogpagos.setBackground(new java.awt.Color(255, 255, 255));
        chkprogpagos.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        chkprogpagos.setText("Programación de Pagos");

        chkseguridad.setBackground(new java.awt.Color(255, 255, 255));
        chkseguridad.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        chkseguridad.setText("Seguridad");

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Acceso al Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N

        tblstusuario.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tblstusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblstusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblstusuarioMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblstusuario);

        lblcont.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblcont.setText("0 Usuarios");

        btnsalir.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnnuevo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttonnuevo.png"))); // NOI18N
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguarda.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnguarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnguarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardaActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuarios.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtapepat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtapemat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(chkestado)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel11)
                                .addGap(43, 43, 43)
                                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel9)
                                .addGap(25, 25, 25)
                                .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(chklibroselectronico))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(chkprogpagos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(chkseguridad))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnguarda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblcont)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txtapepat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtapemat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(chkestado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel11))
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel9))
                            .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(chklibroselectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(chkprogpagos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(chkseguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnguarda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblcont))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenartablausuario() {
        LUsuario lusu = new LUsuario();
        lstusuario = lusu.ListaUsuario();
        modTbdatos.setRowCount(0);
        if (lstusuario.size() > 0) {
            for (int i = 0; i < lstusuario.size(); i++) {
                Object obj[] = new Object[11];
                obj[0] = lstusuario.get(i).getDNI();
                obj[1] = lstusuario.get(i).getNombres();
                obj[2] = lstusuario.get(i).getApePaterno();
                obj[3] = lstusuario.get(i).getApeMaterno();
                obj[4] = lstusuario.get(i).getUsuario();
                obj[5] = lstusuario.get(i).getContra();
                obj[6] = lstusuario.get(i).getEstado();
                obj[7] = lstusuario.get(i).getEmail();
                obj[8] = lstusuario.get(i).getImportar();
                obj[9] = lstusuario.get(i).getExportar();
                obj[10] = lstusuario.get(i).getSeguridad();
                modTbdatos.addRow(obj);
            }
        }
        tblstusuario.setModel(modTbdatos);
        lblcont.setText(tblstusuario.getRowCount() + " Usuario(s)");
    }
    
    private String nomusuario() {
        StringBuilder sbr = new StringBuilder();
        sbr.append(txtnombres.getText().toString().trim().substring(0, 1));
        sbr.append(txtapepat.getText().toString().trim());
        for (int i = 0; i < lstusuario.size(); i++) {
            if (sbr.toString().equalsIgnoreCase(lstusuario.get(i).getUsuario())) {
                sbr.append(txtapemat.getText().toString().trim());
            }
        }
        return sbr.toString().toUpperCase();
    }
    
    private boolean validar() {
        int val = 0;
        if (txtdni.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese DNI.");
            txtdni.requestFocus();
        } else {
            if (txtdni.getText().trim().length() < 8) {
                JOptionPane.showMessageDialog(this, "DNI debe tener 8 caracteres.");
                txtdni.requestFocus();
            } else {
                if (txtnombres.getText().trim().length() == 0) {
                    JOptionPane.showMessageDialog(this, "Ingrese Nombres.");
                    txtnombres.requestFocus();
                } else {
                    if (txtapepat.getText().trim().length() == 0) {
                        JOptionPane.showMessageDialog(this, "Ingrese Apellido Paterno.");
                        txtapepat.requestFocus();
                    } else {
                        if (txtapemat.getText().trim().length() == 0) {
                            JOptionPane.showMessageDialog(this, "Ingrese Apellido Materno.");
                            txtapemat.requestFocus();
                        } else {
                            if (txtcontra.getText().trim().length() == 0) {
                                JOptionPane.showMessageDialog(this, "Ingrese Contraseña.");
                                txtcontra.requestFocus();
                            } else {
                                if (txtcontra.getText().trim().length() < 6) {
                                    JOptionPane.showMessageDialog(this, "Contraseña debe tener un mínimo de 6 caracteres.");
                                    txtcontra.requestFocus();
                                } else {
                                    if (!chklibroselectronico.isSelected() 
                                            && !chkprogpagos.isSelected() 
                                            && !chkseguridad.isSelected()) {
                                        JOptionPane.showMessageDialog(this, "Seleccione al menos uno de los accesos disponibles.");
                                    } else {
                                        val = 1;
                                    }

                                }
                            }
                        }
                    }
                }
            }
        }
        if (val == 1) {
            return true;
        } else {
            return false;
        }
    }
    
    private boolean verificardni(String dni) {
        int rep = 0;
        for (int i = 0; i < lstusuario.size(); i++) {
            if (lstusuario.get(i).getDNI().equalsIgnoreCase(dni)) {
                rep = 1;
            }
        }
        if (rep == 0) {
            return true;
        } else {
            return false;
        }
    }
    
    private void seleccionfila(int fila){
        txtdni.setText(tblstusuario.getValueAt(fila, 0).toString());
        txtnombres.setText(tblstusuario.getValueAt(fila, 1).toString());
        txtapepat.setText(tblstusuario.getValueAt(fila, 2).toString());
        txtapemat.setText(tblstusuario.getValueAt(fila, 3).toString());
        txtusuario.setText(tblstusuario.getValueAt(fila, 4).toString());
        txtcontra.setText(tblstusuario.getValueAt(fila, 5).toString());
        if (tblstusuario.getValueAt(fila, 6).toString().equalsIgnoreCase("ACTIVO")) {
            chkestado.setSelected(true);
        } else {
            chkestado.setSelected(false);
        }
        txtemail.setText(tblstusuario.getValueAt(fila, 7).toString().trim());
        marcarchecks(chklibroselectronico, tblstusuario.getValueAt(fila, 8).toString().trim());
        marcarchecks(chkprogpagos, tblstusuario.getValueAt(fila, 9).toString().trim());
        marcarchecks(chkseguridad, tblstusuario.getValueAt(fila, 10).toString().trim());
        accion=1;
        txtdni.setEditable(false);
    }
    
    private void marcarchecks(JCheckBox chk, String estado){
        if (estado.equalsIgnoreCase("SI")) {
            chk.setSelected(true);
        } else {
            chk.setSelected(false);
        }
    }
    
    private void limpiar(){
        txtdni.setText("");
        txtnombres.setText("");
        txtapepat.setText("");
        txtapemat.setText("");
        txtemail.setText("");
        chkestado.setSelected(true);
        txtusuario.setText("");
        txtcontra.setText("");
        chkprogpagos.setSelected(false);
        chklibroselectronico.setSelected(false);
        chkseguridad.setSelected(false);
        accion=0;
        txtdni.setEditable(true);
        txtdni.requestFocus();
    }
    
    private void txtdniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_TAB){
            txtnombres.requestFocus();
        }
    }//GEN-LAST:event_txtdniKeyReleased

    private void txtdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
        if (txtdni.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdniKeyTyped

    private void txtnombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_TAB){
            txtapepat.requestFocus();
        }
    }//GEN-LAST:event_txtnombresKeyReleased

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'A' || c > 'Z') && (c < 'a' || c > 'z') && (evt.getKeyCode()==KeyEvent.VK_SPACE)) {
            evt.consume();
        }
        if (txtnombres.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapepatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapepatKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_TAB){
            txtapemat.requestFocus();
        }
    }//GEN-LAST:event_txtapepatKeyReleased

    private void txtapepatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapepatKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'A' || c > 'Z') && (c < 'a' || c > 'z') && (evt.getKeyCode()==KeyEvent.VK_SPACE)) {
            evt.consume();
        }
        if (txtapepat.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txtapepatKeyTyped

    private void txtapematKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapematKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_TAB){
            txtemail.requestFocus();
        }
    }//GEN-LAST:event_txtapematKeyReleased

    private void txtapematKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapematKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'A' || c > 'Z') && (c < 'a' || c > 'z') && (evt.getKeyCode()==KeyEvent.VK_SPACE)) {
            evt.consume();
        }
        if (txtapepat.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txtapematKeyTyped

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_TAB){
            txtcontra.requestFocus();
        }
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyTyped

    private void txtcontraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontraKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_TAB){
            btnguarda.requestFocus();
        }
    }//GEN-LAST:event_txtcontraKeyReleased

    private void txtusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioKeyReleased

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioKeyTyped

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnguardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardaActionPerformed
        // TODO add your handling code here:
        if(validar()){
            EUsuario objusu=new EUsuario();
            objusu.setDNI(txtdni.getText().trim());
            objusu.setNombres(txtnombres.getText().toUpperCase().trim());
            objusu.setApePaterno(txtapepat.getText().toUpperCase().trim());
            objusu.setApeMaterno(txtapemat.getText().toUpperCase().trim());
            objusu.setEmail(txtemail.getText().trim());
            objusu.setEstado((chkestado.isSelected()) ? "ACTIVO" : "INACTIVO");
            objusu.setContra(txtcontra.getText().trim());
            objusu.setImportar((chklibroselectronico.isSelected()) ? "SI" : "NO");
            objusu.setExportar((chkprogpagos.isSelected()) ? "SI" : "NO");
            objusu.setSeguridad((chkseguridad.isSelected()) ? "SI" : "NO");
            LUsuario lusu = new LUsuario();
            if(accion==0){
                if(verificardni(objusu.getDNI())){
                    System.out.println(nomusuario());
                    objusu.setUsuario(nomusuario());
                    if (JOptionPane.showConfirmDialog(null, "Se va GRABAR el Usuario " + objusu.getUsuario() + ". ¿Desea Continuar?", "Confirmar", JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_OPTION)) {
                        if(lusu.InsertarUsuario(objusu)){
                            JOptionPane.showMessageDialog(this, "Se grabó correctamente al usuario " + objusu.getUsuario() + ".");
                            limpiar();
                            llenartablausuario();
                        }else{
                            JOptionPane.showMessageDialog(this, "Error de tipo de Dato y/o Conexión de BD.");
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "DNI ingresado ya se encuentra registrado.");
                    txtdni.requestFocus();
                }
            }else{
                objusu.setUsuario(txtusuario.getText().toUpperCase().trim());
                if (JOptionPane.showConfirmDialog(null, "Se va MODIFICAR el Usuario " + objusu.getUsuario() + ". ¿Desea Continuar?", "Confirmar", JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_OPTION)) {
                    if (lusu.ActualizarUsuario(objusu)) {
                        JOptionPane.showMessageDialog(this, "Se actualizó correctamente al usuario " + objusu.getUsuario() + ".");
                        limpiar();
                        llenartablausuario();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error de tipo de Dato y/o Conexión de BD.");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnguardaActionPerformed

    private void tblstusuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstusuarioMouseReleased
        // TODO add your handling code here:
        int fila = tblstusuario.getSelectedRow();
        if (fila >= 0) {
            seleccionfila(fila);
        }
    }//GEN-LAST:event_tblstusuarioMouseReleased

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnnuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguarda;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JCheckBox chkestado;
    private javax.swing.JCheckBox chklibroselectronico;
    private javax.swing.JCheckBox chkprogpagos;
    private javax.swing.JCheckBox chkseguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcont;
    private javax.swing.JTable tblstusuario;
    private javax.swing.JTextField txtapemat;
    private javax.swing.JTextField txtapepat;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
