/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Panel.Retencion;

import Capa_Entidades.EDataRetencion;
import Capa_Logica.LImportar;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import jxl.Sheet;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.biff.CountryCode;
import jxl.read.biff.BiffException;

/**
 *
 * @author EXPERTYA
 */
public class InterFrmImportRetencion extends javax.swing.JInternalFrame {
    ArrayList<EDataRetencion> lstretencion=new ArrayList<>();
     String titulos[] = {"Correlativo", "Razon Social", "RUC", "Fecha", "Nro.Doc.",
         "Importe","% Reten.","Retencion","SUNAT","NETO"};
    DefaultTableModel modTbdatos = new DefaultTableModel(titulos, 0);
    DecimalFormatSymbols simbolo = new DecimalFormatSymbols();
    /**
     * Creates new form InterFrmImportRetencion
     */
    public InterFrmImportRetencion() {
        initComponents();
        tblstretenciones.setModel(modTbdatos);
        simbolo.setDecimalSeparator('.');
        simbolo.setGroupingSeparator(',');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstretenciones = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        btnguarda = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jButton1.setText("Importar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblstretenciones.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tblstretenciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblstretenciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        btnguarda.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnguarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnguarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnguarda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnguarda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String mifecha(String lafecha){
        String fecha="";
        if(lafecha.trim().length()==8){
            fecha=lafecha.trim().substring(0, 2)+"-"+lafecha.trim().substring(3, 5)+"-"+
                    "20"+lafecha.trim().substring(6, 8);
        }
        return fecha;
    }
    
    private void llenartabla(){
        DecimalFormat formato = new DecimalFormat("###, ##0.00", simbolo);
        modTbdatos.setRowCount(0);
        if(lstretencion.size()>0){
            for (int i = 0; i < lstretencion.size(); i++) {
                Object obj[]=new Object[10];
                obj[0]=lstretencion.get(i).getCorrelativo();
                obj[1]=lstretencion.get(i).getRazonSocial();
                obj[2]=lstretencion.get(i).getRUC();
                obj[3]=mifecha(lstretencion.get(i).getFecha().trim());
                obj[4]=lstretencion.get(i).getDoc();
                obj[5]=formato.format(Double.parseDouble(lstretencion.get(i).getImporte()));
                obj[6]=lstretencion.get(i).getPorcentRetenc();
                obj[7]=formato.format(Double.parseDouble(lstretencion.get(i).getRetencion()));
                obj[8]=formato.format(Double.parseDouble(lstretencion.get(i).getSUNAT()));
                obj[9]=formato.format(Double.parseDouble(lstretencion.get(i).getNeto()));
                modTbdatos.addRow(obj);
            }
        }
        tblstretenciones.setModel(modTbdatos);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser jF1 = new javax.swing.JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("XLS files", "xls");
        jF1.setFileFilter(filtro);
        String ruta = "";
        try {
            if (jF1.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                ruta = jF1.getSelectedFile().getAbsolutePath();
                System.out.println(ruta);
                int val=0;
                WorkbookSettings wbSettings = new WorkbookSettings();
                wbSettings.setEncoding("ISO-8859-1");
                wbSettings.setLocale(new Locale("es", "ES"));
                wbSettings.setExcelDisplayLanguage("ES");
                wbSettings.setExcelRegionalSettings("ES");
                wbSettings.setCharacterSet(CountryCode.SPAIN.getValue());
                Workbook workbook = Workbook.getWorkbook(new File(ruta), wbSettings);
                lstretencion.removeAll(lstretencion);
                Sheet sheet = workbook.getSheet(0);
//                if(!esNumeroEntero(sheet.getCell(0, 18).getContents().trim())){   
//                    val=1;
//                    JOptionPane.showMessageDialog(this, "El archivo que intenta cargar no cuenta con el formato adecuado.");
//                }
                for (int fila = 29; fila < 36; fila++) {
                    //recorremos las filas
                    if(sheet.getCell(0, fila).getContents().toString().trim().length()>0){
                        EDataRetencion objdata=new EDataRetencion();
                        objdata.setCorrelativo(Integer.valueOf(sheet.getCell(0, fila).getContents()));
                        objdata.setRazonSocial(sheet.getCell(1, fila).getContents().trim());
                        objdata.setRUC(sheet.getCell(2, fila).getContents().trim());
                        objdata.setFecha(sheet.getCell(3, fila).getContents().trim());
                        objdata.setDoc(sheet.getCell(4, fila).getContents().trim());
                        objdata.setImporte(Double.valueOf(sheet.getCell(5, fila).getContents().trim().replace(".", "").replace(",", ".")).toString());
                        objdata.setPorcentRetenc(sheet.getCell(6, fila).getContents().trim());
                        objdata.setRetencion(Double.valueOf(sheet.getCell(7, fila).getContents().trim().replace(".", "").replace(",", ".")).toString());
                        objdata.setSUNAT(Double.valueOf(sheet.getCell(8, fila).getContents().trim().replace(".", "").replace(",", ".")).toString());
                        objdata.setNeto(Double.valueOf(sheet.getCell(10, fila).getContents().trim().replace(".", "").replace(",", ".")).toString());
                        lstretencion.add(objdata);
                    }
                }
                for (int fila = 44; fila < 47; fila++) {
                    //recorremos las filas
                    if(sheet.getCell(0, fila).getContents().toString().trim().length()>0){
                        EDataRetencion objdata=new EDataRetencion();
                        objdata.setCorrelativo(Integer.valueOf(sheet.getCell(0, fila).getContents()));
                        objdata.setRazonSocial(sheet.getCell(1, fila).getContents().trim());
                        objdata.setRUC(sheet.getCell(2, fila).getContents().trim());
                        objdata.setFecha(sheet.getCell(3, fila).getContents().trim());
                        objdata.setDoc(sheet.getCell(4, fila).getContents().trim());
                        objdata.setImporte(Double.valueOf(sheet.getCell(5, fila).getContents().trim().replace(".", "").replace(",", ".")).toString());
                        objdata.setPorcentRetenc(sheet.getCell(6, fila).getContents().trim());
                        objdata.setRetencion(Double.valueOf(sheet.getCell(7, fila).getContents().trim().replace(".", "").replace(",", ".")).toString());
                        objdata.setSUNAT(Double.valueOf(sheet.getCell(8, fila).getContents().trim().replace(".", "").replace(",", ".")).toString());
                        objdata.setNeto(Double.valueOf(sheet.getCell(10, fila).getContents().trim().replace(".", "").replace(",", ".")).toString());
                        lstretencion.add(objdata);
                    }
                }
                llenartabla();
            }
        } catch (HeadlessException | IOException | BiffException | IndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "El archivo que intenta cargar no cuenta con el formato adecuado.");
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnguardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardaActionPerformed
        // TODO add your handling code here:
        if(lstretencion.size()>0){
            for (int i = 0; i < lstretencion.size(); i++) {
                LImportar lim=new LImportar();
                if(lim.InsertarDataRetencionDetalle(lstretencion.get(i))){
                    System.out.println("Grabado: "+(i+1));
                }
            }
        }
    }//GEN-LAST:event_btnguardaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguarda;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblstretenciones;
    // End of variables declaration//GEN-END:variables
}
