/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Presentacion;

import Capa_Conexion.ConexionBD;
import Capa_Entidades.EUsuario;
import Capa_ProgPago.Menu_PrincipalPrg;
import Capa_Logica.LUsuario;
import Capa_Logica.SesionUsuario;
import Capa_Panel.Importar.Menu_Importar;
import Capa_Panel.Seguridad.InterFrmCambioContra;
import Capa_Panel.Seguridad.Menu_Seguridad;
import Capa_ProgPago.Menu;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrmLogin extends javax.swing.JFrame {
    
    public String modulo;
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Acceso al Sistema");
        setIconImage(new ImageIcon(getClass().getResource("/img/Santander.png")).getImage());
        ConexionBD con=new ConexionBD("");
        con.leer_ini();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private boolean validar(){
        if(txtUsuario.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Ingrese Usuario.");
            txtUsuario.requestFocus();
            return false;
        }else{
            if(txtpass.getText().trim().length()==0){
                JOptionPane.showMessageDialog(this, "Ingrese Contraseña.");
                txtpass.requestFocus();
                return false;
            }else{
                return true;
            }
        }
    }
    
    private void login(){
        if (validar()) {
            LUsuario lusu=new LUsuario();
            EUsuario objusu=new EUsuario();
            ArrayList<EUsuario> lstusu=new ArrayList<>();
            lstusu=lusu.ListaUsuario();
            int existe=0;
            for (int i = 0; i < lstusu.size(); i++) {
                if(txtUsuario.getText().trim().equalsIgnoreCase(lstusu.get(i).getUsuario())){
                    existe=1;
                }
            }
            if (existe == 1) {
                objusu = lusu.Login(txtUsuario.getText(), txtpass.getText());
                Object obj = objusu;
                if (obj != null) {
                    if (objusu.getImportar().equalsIgnoreCase("NADA")) {
                        JOptionPane.showMessageDialog(this, "Contraseña incorrecta.");
                    } else {
                        SesionUsuario.misesion = objusu;
                        if(modulo.equalsIgnoreCase("LIBROS")){
                            if(objusu.getImportar().equalsIgnoreCase("SI")){
                                MenuLibrosElectronico menu=new MenuLibrosElectronico();
                                menu.setVisible(true);
                            }else{
                                JOptionPane.showMessageDialog(this, "No cuenta con autorización para entrar al modulo de Libros Electrónicos.");
                            }
                        }
                        if(modulo.equalsIgnoreCase("PAGOS")){
                            if(objusu.getExportar().equalsIgnoreCase("SI")){
                                Menu menu=new Menu();
                                menu.setVisible(true);
                            }else{
                                JOptionPane.showMessageDialog(this, "No cuenta con autorización para entrar al modulo de Porgramación de Pagos.");
                            }
                        }
                        if(modulo.equalsIgnoreCase("SEGURIDAD")){
                            if(objusu.getSeguridad().equalsIgnoreCase("SI")){
                                Menu_Seguridad menu=new Menu_Seguridad();
                                menu.setVisible(true);
                            }else{
                                JOptionPane.showMessageDialog(this, "No cuenta con autorización para entrar al modulo de Seguridad.");
                            }
                        }
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta.");
                }                
            } else {
                JOptionPane.showMessageDialog(this, "El Usuario que ingreso no existe.");
            }
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtSalir = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sant.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 210, 70));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("Clave");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(null);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 25));

        txtSalir.setBackground(new java.awt.Color(255, 255, 255));
        txtSalir.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtSalir.setText("Salir");
        txtSalir.setBorder(null);
        txtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalirActionPerformed(evt);
            }
        });
        jPanel1.add(txtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 100, 25));

        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, -1));

        txtpass.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
        });
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Cambiar Contraseña");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_txtSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             login();
         }
    }//GEN-LAST:event_txtpassKeyReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        InterFrmCambioContra cambiocontra=new InterFrmCambioContra();
        cambiocontra.txtusu.setText(txtUsuario.getText());
        cambiocontra.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txtSalir;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
