/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Presentacion;

import Capa_Logica.SesionUsuario;
import Capa_Logica.Reloj;
import Capa_Panel.Consulta.Menu_Consulta;
import Capa_Panel.Exportar.FrmExportar;
import Capa_Panel.Formatear.Menu_Formatear;
import Capa_Panel.Importar.Menu_Importar;
import Capa_Panel.Seguridad.Menu_Seguridad;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public Menu_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/Santander.png")).getImage());
        this.setTitle("SANTADER CONSUMO PERÚ S.A.C.");
        Reloj hilo = new Reloj(txthora);
        hilo.start();
//        btnconsulta.setEnabled(false);
//        btnexportar.setEnabled(false);
//        btnformatear.setEnabled(false);
//        btnimportar.setEnabled(false);
//        btnseguridad.setEnabled(false);
        txtfecha.setText(fecha());
        txtConexion.setText("Sin Conexión");
        verconexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void verconexion(){
        Object obj=SesionUsuario.bddatos.getIp();
         if (obj == null) {
             txtConexion.setText("SIN CONEXIÓN");
         } else {
             txtConexion.setText(SesionUsuario.bddatos.getIp() + " / " + SesionUsuario.bddatos.getNombd());
         }
    }
    
    public String fecha() {
        GregorianCalendar fecha = new GregorianCalendar();
        int dia = fecha.get(fecha.DAY_OF_MONTH);
        int dia2=fecha.get(fecha.DAY_OF_WEEK);
        int mes = fecha.get(fecha.MONTH);
        int año = fecha.get(fecha.YEAR);
        String mifecha =nombredia2(dia2)+" "+String.valueOf(dia) + " de " + nombremes(mes) + " de " + String.valueOf(año);
        return mifecha;
    }

    public String nombredia2(int dia){
         switch (dia) {
            case 1:
                return "Domingo";
            case 2:
                return "Lunes";
            case 3:
                return "Martes";
            case 4:
                return "Miércoles";
            case 5:
                return "Jueves";
            case 6:
                return "Viernes";
            case 7:
                return "Sábado";
        }
        return null;
    }
    
    public String nombremes(int mes) {
        switch (mes) {
            case 0:
                return "Enero";
            case 1:
                return "Febrero";
            case 2:
                return "Marzo";
            case 3:
                return "Abril";
            case 4:
                return "Mayo";
            case 5:
                return "Junio";
            case 6:
                return "Julio";
            case 7:
                return "Agosto";
            case 8:
                return "Setiembre";
            case 9:
                return "Octubre";
            case 10:
                return "Noviembre";
            case 11:
                return "Diciembre";
        }
        return "Error";
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnimportar = new javax.swing.JButton();
        btnexportar = new javax.swing.JButton();
        btnconsulta = new javax.swing.JButton();
        btnseguridad = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnacercade = new javax.swing.JButton();
        btnformatear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txthora = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        txtConexion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(620, 350));
        setMinimumSize(new java.awt.Dimension(620, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnimportar.setBackground(new java.awt.Color(153, 153, 153));
        btnimportar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnimportar.setText("            1. Importar");
        btnimportar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnimportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnimportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 140, 31));

        btnexportar.setBackground(new java.awt.Color(153, 153, 153));
        btnexportar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnexportar.setText("            3. Exportar");
        btnexportar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnexportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 140, 31));

        btnconsulta.setBackground(new java.awt.Color(153, 153, 153));
        btnconsulta.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnconsulta.setText("            4. Consulta");
        btnconsulta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 140, 31));

        btnseguridad.setBackground(new java.awt.Color(153, 153, 153));
        btnseguridad.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnseguridad.setText("            5. Seguridad");
        btnseguridad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnseguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseguridadActionPerformed(evt);
            }
        });
        getContentPane().add(btnseguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 140, 31));

        btnsalir.setBackground(new java.awt.Color(153, 153, 153));
        btnsalir.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setToolTipText("");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 137, 31));

        btnacercade.setBackground(new java.awt.Color(153, 153, 153));
        btnacercade.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnacercade.setText("Acerca de");
        btnacercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacercadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnacercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 137, 31));

        btnformatear.setBackground(new java.awt.Color(153, 153, 153));
        btnformatear.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnformatear.setText("            2. Formatear");
        btnformatear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnformatear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformatearActionPerformed(evt);
            }
        });
        getContentPane().add(btnformatear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 140, 31));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 54, 200, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIBROS ELECTRÓNICOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SANTANDER_LE.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txthora.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        txthora.setForeground(new java.awt.Color(255, 255, 255));
        txthora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txthora.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 5, 70, 20));

        txtfecha.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(255, 255, 255));
        txtfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 5, 170, 20));

        txtConexion.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        txtConexion.setForeground(new java.awt.Color(255, 255, 255));
        txtConexion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txtConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 300, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 610, 30));

        jMenuBar1.setBorder(null);

        jMenu1.setText("LIBROS ELECTRÓNICOS 1.0");
        jMenu1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnseguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseguridadActionPerformed
        // TODO add your handling code here:
        Menu_Seguridad ms=new Menu_Seguridad();
        ms.setVisible(true);
    }//GEN-LAST:event_btnseguridadActionPerformed

    private void btnconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaActionPerformed
        // TODO add your handling code here:
        Menu_Consulta mc=new Menu_Consulta();
        mc.setVisible(true);
    }//GEN-LAST:event_btnconsultaActionPerformed

    private void btnimportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimportarActionPerformed
        // TODO add your handling code here:
        Menu_Importar mi=new Menu_Importar();
        mi.setVisible(true);
    }//GEN-LAST:event_btnimportarActionPerformed

    private void btnexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportarActionPerformed
        // TODO add your handling code here:
        FrmExportar export=new FrmExportar();
        export.setVisible(true);
    }//GEN-LAST:event_btnexportarActionPerformed

    private void btnacercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacercadeActionPerformed
        // TODO add your handling code here:
        JDAcercaDe jda=new JDAcercaDe(this, true);
        jda.setVisible(true);
    }//GEN-LAST:event_btnacercadeActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        System.exit(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnformatearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformatearActionPerformed
        // TODO add your handling code here:
      Menu_Formatear formatear=new Menu_Formatear();
      formatear.setVisible(true);
    }//GEN-LAST:event_btnformatearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacercade;
    public javax.swing.JButton btnconsulta;
    public javax.swing.JButton btnexportar;
    public javax.swing.JButton btnformatear;
    public javax.swing.JButton btnimportar;
    private javax.swing.JButton btnsalir;
    public javax.swing.JButton btnseguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtConexion;
    private javax.swing.JLabel txtfecha;
    private javax.swing.JLabel txthora;
    // End of variables declaration//GEN-END:variables
}
