/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Panel.Formatear;

import Capa_Entidades.EFormatoDAOTVentas;
import Capa_Logica.LImportar;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXPERTYA
 */
public class InterFrmFormatearDAOTVentas extends javax.swing.JInternalFrame {
    ArrayList<EFormatoDAOTVentas> lstdaot=new ArrayList<>();
    String titulos[] = {"Fila", "TipoDocDeclarante", "NroDocDeclarante", "Año", "TipoPersona", "TipoDocDeclarado", 
         "Nro.Doc.Declarado",
        "Monto", "Nombres", "RazonSocial", "Condicion"};
    DefaultTableModel modTbdatos = new DefaultTableModel(titulos, 0);
    /**
     * Creates new form InterFrmFormatearDAOTVentas
     */
    public InterFrmFormatearDAOTVentas() {
        initComponents();
        tblstdaot.setModel(modTbdatos);
        tblstdaot.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    private boolean Contar3palotes(String nombres) {
        char[] arrayChar = nombres.toCharArray();
        int contador = 0;
        for (int i = 0; i < arrayChar.length; i++) {
            if (arrayChar[i] == '|') {
                contador = contador + 1;
            }
        }
        if(contador==3){
            return true;
        }else{
            return false;
        }
    }

    private void llenartabla(){
        LImportar li =new LImportar();
        modTbdatos.setRowCount(0);
        lstdaot=li.ListarDaotVentas();
        double montototal=0.0;
        int nuevemillones=0;
        if(lstdaot.size()>0){
            for (int i = 0; i < lstdaot.size(); i++) {
                Object obj[]=new Object[11];
                obj[0]=lstdaot.get(i).getFila();
                obj[1]=lstdaot.get(i).getTipoDocSantander();
                obj[2]=lstdaot.get(i).getRucSantander();
                obj[3] = lstdaot.get(i).getAño();
                if (lstdaot.get(i).getTipoPersona().equalsIgnoreCase("06") || lstdaot.get(i).getTipoPersona().equalsIgnoreCase("")) {
                    obj[4] = "02";
                } else {
                    obj[4] = "01";
                }
                if(lstdaot.get(i).getTipoPersona().trim().length()>0){
                    obj[5]=Integer.valueOf(lstdaot.get(i).getTipoPersona());
                }else{
                    obj[5]="-";
                }
                
                obj[6]=lstdaot.get(i).getRucCliente();
                obj[7]=lstdaot.get(i).getMonto();
                montototal=montototal+lstdaot.get(i).getMonto();
                if(montototal>9000000){
                    nuevemillones=nuevemillones+1;
                    montototal=montototal-9000000;
                }
                obj[8]=lstdaot.get(i).getNombresSinSeparar();
                obj[9]=lstdaot.get(i).getRazonSocial();
                if(lstdaot.get(i).getNombresSinSeparar().trim().length()>0){
                    if(Contar3palotes(lstdaot.get(i).getNombresSinSeparar())){
                        obj[10]="";
                    }else{
                        obj[10]="FORMATEARMANUALMENTE";
                    }
                }else{
                    obj[10]="";
                }
                modTbdatos.addRow(obj);
            }
        }
        tblstdaot.setModel(modTbdatos);
        System.out.println("9 millones: " + nuevemillones+ " resto: "+ montototal);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblstdaot = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtruta = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        tblstdaot.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tblstdaot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblstdaot);

        jButton1.setText("Llenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Select");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(181, 181, 181)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        llenartabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser jF1 = new javax.swing.JFileChooser();
        String ruta = "";
        try {
                jF1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                if (jF1.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                    ruta = jF1.getSelectedFile().getAbsolutePath();
                    String nombrearchivo="DAOTVENTAS";
                txtruta.setText(ruta +"\\"+ nombrearchivo+".txt");
            }
        } catch (Exception ex) {
            ex.getMessage();
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          File archivo = new File(txtruta.getText().trim());
        try {
            FileWriter escribir = new FileWriter(archivo, true);
            for (int i = 0; i < tblstdaot.getRowCount(); i++) {
                String filastring=tblstdaot.getValueAt(i, 0).toString()+"|"+
                        tblstdaot.getValueAt(i, 1).toString()+"|"+
                        tblstdaot.getValueAt(i, 2).toString()+"|"+
                        tblstdaot.getValueAt(i, 3).toString()+"|"+
                        tblstdaot.getValueAt(i, 4).toString()+"|"+
                        tblstdaot.getValueAt(i, 5).toString()+"|"+
                        tblstdaot.getValueAt(i, 6).toString()+"|"+
                        tblstdaot.getValueAt(i, 7).toString()+"|"+
                        tblstdaot.getValueAt(i, 8).toString()+"|"+
                        tblstdaot.getValueAt(i, 9).toString()+"|"+
                        tblstdaot.getValueAt(i, 10).toString();
                escribir.write(filastring);
                escribir.write("\r\n");    
            }
            escribir.close();
        } catch (IOException ex) {
            Logger.getLogger(InterFrmFormatearDAOTVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblstdaot;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
