/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_ProgPago;

import Capa_Entidades.EComprobante;
import Capa_Entidades.EConsolidado;
import Capa_Entidades.EProgPagosCabecera;
import Capa_Logica.LProgPagosCabecera;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXPERTYA
 */
public class Consultatxt extends javax.swing.JInternalFrame {
    ArrayList<EConsolidado> lstconsolidado = new ArrayList<>();
    ArrayList<EComprobante> lstdetalle = new ArrayList();
    ArrayList<EProgPagosCabecera> lstcabecera = new ArrayList<>();
    String titulos[] = {"CodProg", "Moneda", "Monto", "Fecha", "UsuCrea", "FecCrea"};
    DefaultTableModel modTbdatos = new DefaultTableModel(titulos, 0);
    String titulos3[] = {"CodProg", "CodCompr", "TipoComprobante", "NumComp", "Fecha", "DocProv", "Glosa", "CompSujeto",
        "FormaPago", "MontoSoles", "MontoDolares", "Estado", "Banco", "Moneda", "CtaBancaria"};
    DefaultTableModel modTbdatos3 = new DefaultTableModel(titulos3, 0);
    DecimalFormatSymbols simbolo = new DecimalFormatSymbols();
    /**
     * Creates new form Exportartxt
     */
    public Consultatxt() {
        initComponents();
        tbcabprogramacion.setModel(modTbdatos);
        tblstdetprogramacion.setModel(modTbdatos3);
        this.setTitle("Consulta de Exportación.");
        setFrameIcon(new ImageIcon(getClass().getResource("/img/Santander.png")));
        tblstdetprogramacion.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        simbolo.setDecimalSeparator('.');
        simbolo.setGroupingSeparator(',');
        Date hoy =new Date();
        dcfechaini.setDate(hoy);
        dcfechafin.setDate(hoy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void llenarcab() {
        LProgPagosCabecera lo = new LProgPagosCabecera();
        lstcabecera = lo.BuscarExportacion(fechaformato(dcfechaini.getDate()),fechaformato(dcfechafin.getDate()));
        if (lstcabecera.size() > 0) {
            listacomprobante();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron registros.");
            lstcabecera.removeAll(lstcabecera);
            listacomprobante();
        }
    }
    
     private void listacomprobante() {
         DecimalFormat formato = new DecimalFormat("#####0.00",simbolo);
        modTbdatos.setRowCount(0);
        if (lstcabecera.size() > 0) {
            for (int i = 0; i < lstcabecera.size(); i++) {
                EProgPagosCabecera at;
                at = lstcabecera.get(i);
                Object nuevafila[] = new Object[6];
                nuevafila[0] = at.getCod_programacion();
                nuevafila[1] = at.getMoneda();
                nuevafila[2] = formato.format(at.getMonto());
                nuevafila[3] = at.getFecha();
                nuevafila[4] = at.getUsucrea();
                nuevafila[5] = at.getFeccrea();
                modTbdatos.addRow(nuevafila);
            }
        }
        tbcabprogramacion.setModel(modTbdatos);
         lblnumcabprog.setText(tbcabprogramacion.getRowCount() + " Registro(s)");
    }
     
      private void listadetalle() {
        modTbdatos3.setRowCount(0);
        if (lstdetalle.size() > 0) {
            for (int i = 0; i < lstdetalle.size(); i++) {
                Object nuevafila[] = new Object[15];
                nuevafila[0] = lstdetalle.get(i).getCodProgramacion();
                nuevafila[1] = lstdetalle.get(i).getCodComprobante();
                nuevafila[2] = lstdetalle.get(i).getTipoComprobante();
                nuevafila[3] = lstdetalle.get(i).getNumComprobante();
                nuevafila[4] = lstdetalle.get(i).getFechaComprobante();
                nuevafila[5] = lstdetalle.get(i).getDocProveedor();
                nuevafila[6] = lstdetalle.get(i).getGlosaComprante();
                nuevafila[7] = lstdetalle.get(i).getComprobanteSujeto();
                nuevafila[8] = lstdetalle.get(i).getFormaPago();
                nuevafila[9] = lstdetalle.get(i).getMontoPagar();
                nuevafila[10] = lstdetalle.get(i).getMontoPagarDOL();
                nuevafila[11] = lstdetalle.get(i).getEstado();
                nuevafila[12] = lstdetalle.get(i).getUsuModi();
                nuevafila[13] = lstdetalle.get(i).getNomMoneda();
                nuevafila[14] = lstdetalle.get(i).getCuentasoles();
                modTbdatos3.addRow(nuevafila);
            }
        }
        tblstdetprogramacion.setModel(modTbdatos3);
         lblnumdetalleprog1.setText(tblstdetprogramacion.getRowCount() + " Registro(s)");
    }
      
      String fechaformato(Date fecha) {
        String fec = new SimpleDateFormat("dd-MM-yyyy").format(fecha);
        return fec;
    }
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        btnsalir1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcabprogramacion = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblnumcabprog = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblstdetprogramacion = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblnumdetalleprog1 = new javax.swing.JLabel();
        dcfechaini = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dcfechafin = new com.toedter.calendar.JDateChooser();
        btneliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel2.setBackground(new java.awt.Color(255, 0, 15));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA DE EXPORTACIÓN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnsalir1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnsalir1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btnsalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir1ActionPerformed(evt);
            }
        });

        tbcabprogramacion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tbcabprogramacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbcabprogramacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbcabprogramacionMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbcabprogramacion);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setBackground(new java.awt.Color(255, 204, 0));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CABECERA DE EXPORTACIÓN");

        lblnumcabprog.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblnumcabprog.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblnumcabprog.setText("0 Registro (s).");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnumcabprog, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnumcabprog))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblstdetprogramacion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tblstdetprogramacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblstdetprogramacion);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setBackground(new java.awt.Color(255, 204, 0));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DETALLE DE EXPORTACIÓN");

        lblnumdetalleprog1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblnumdetalleprog1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblnumdetalleprog1.setText("0 Registro (s).");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblnumdetalleprog1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnumdetalleprog1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dcfechaini.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("Fecha Inicial");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel6.setText("Fecha Final");

        dcfechafin.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jLabel3)
                            .addGap(12, 12, 12)
                            .addComponent(dcfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel6)
                            .addGap(12, 12, 12)
                            .addComponent(dcfechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnsalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcfechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        llenarcab();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalir1ActionPerformed

    private void tbcabprogramacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcabprogramacionMouseReleased
        // TODO add your handling code here:
        int fila= tbcabprogramacion.getSelectedRow();
        if (fila >= 0) {
            LProgPagosCabecera lp = new LProgPagosCabecera();
            lstdetalle = lp.lstdetalleprg(Integer.valueOf(tbcabprogramacion.getValueAt(fila, 0).toString()));
            listadetalle();
       }
    }//GEN-LAST:event_tbcabprogramacionMouseReleased

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        int fila=tbcabprogramacion.getSelectedRow();
        if(fila>=0){
            if (JOptionPane.showConfirmDialog(this, "Se va Eliminar el Registro de Exportación. ¿Desea Continuar?", "Confirmar", JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_OPTION)) {
                 LProgPagosCabecera lp = new LProgPagosCabecera();
                 if(lp.EliminarDataExportada(Integer.valueOf(tbcabprogramacion.getValueAt(fila, 0).toString()))){
                     llenarcab();
                     JOptionPane.showMessageDialog(this, "Se Elimino correctamente el Registro de Exportación.");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione Programación que desea eliminar.");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnsalir1;
    private com.toedter.calendar.JDateChooser dcfechafin;
    private com.toedter.calendar.JDateChooser dcfechaini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblnumcabprog;
    private javax.swing.JLabel lblnumdetalleprog1;
    private javax.swing.JTable tbcabprogramacion;
    private javax.swing.JTable tblstdetprogramacion;
    // End of variables declaration//GEN-END:variables
}
