/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_ProgPago;

import Capa_Entidades.EProveedor;
import Capa_Logica.LAgenteRetenedores;
import Capa_Logica.LComprobante;
import Capa_Logica.LProveedor;
import Capa_Logica.SesionUsuario;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXPERTYA
 */
public class ConsultaProveedor extends javax.swing.JInternalFrame {
     String titulos[] = {"DocProveedor", "TipoDoc", 
         "RazonSocial","Direccion","Telefono","Contacto",
         "CorreoContacto","Banco","CTASoles","CTADolares","CCISoles","CCIDolares"};
      DefaultTableModel modTbdatos = new DefaultTableModel(titulos, 0);
       ArrayList<EProveedor> lstproveedor = new ArrayList<>();
     ArrayList<EProveedor> lisp = new ArrayList<>();
      ArrayList<EProveedor> lispro = new ArrayList<>();
     int opc=0;
     int fila = 1;
     public int otrofrm=0;
     
    /**
     * Creates new form ConsultaProveedor
     */
    public ConsultaProveedor() {
        initComponents();
          this.setLocation(230, 50);
        this.setTitle("Seleccionar Proveedor.");
        setFrameIcon(new ImageIcon(getClass().getResource("/img/Santander.png")));
        tblstproveedores.setModel(modTbdatos);
         tblstproveedores.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblstproveedores.getTableHeader().setReorderingAllowed(false);
        tblstproveedores.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblstproveedores.getColumnModel().getColumn(1).setPreferredWidth(40);
        tblstproveedores.getColumnModel().getColumn(2).setPreferredWidth(600);
         tblstproveedores.getColumnModel().getColumn(3).setPreferredWidth(300);
        tblstproveedores.getColumnModel().getColumn(4).setPreferredWidth(75);
        tblstproveedores.getColumnModel().getColumn(5).setPreferredWidth(75);
         tblstproveedores.getColumnModel().getColumn(6).setPreferredWidth(75);
        tblstproveedores.getColumnModel().getColumn(7).setPreferredWidth(75);
        tblstproveedores.getColumnModel().getColumn(8).setPreferredWidth(75);
         tblstproveedores.getColumnModel().getColumn(9).setPreferredWidth(75);
        tblstproveedores.getColumnModel().getColumn(10).setPreferredWidth(75);
        tblstproveedores.getColumnModel().getColumn(11).setPreferredWidth(75);
        
        
        
        listaproveedor();
    }

    private void listaproveedor(){
        if(opc==0){
        LProveedor lpro=new LProveedor();
            lstproveedor=lpro.listaProveedor();
        }
                  modTbdatos.setRowCount(0);
                if(lstproveedor.size()>0){
             for(int i=0;i<lstproveedor.size();i++){
                 Object nuevafila[] = new Object[13];
                 nuevafila[0] = lstproveedor.get(i).getDocProveedor();
                 nuevafila[1] = lstproveedor.get(i).getTipoDocProveedor();
                 nuevafila[2] = lstproveedor.get(i).getRazonSocial();
                 nuevafila[3] = lstproveedor.get(i).getDireccion();
                 nuevafila[4] = lstproveedor.get(i).getTelefono();
                 nuevafila[5] = lstproveedor.get(i).getContacto();
                 nuevafila[6] = lstproveedor.get(i).getCorreoContacto();
                 nuevafila[7] = lstproveedor.get(i).getNomBanco();
                 nuevafila[8] = lstproveedor.get(i).getCTASoles();
                 nuevafila[9] = lstproveedor.get(i).getCTADolares();
                 nuevafila[10] = lstproveedor.get(i).getCCISoles();
                 nuevafila[11] = lstproveedor.get(i).getCCIDolares();
                 
                 modTbdatos.addRow(nuevafila);
             }
        }
        tblstproveedores.setModel(modTbdatos);
        lblnroregistros.setText(tblstproveedores.getRowCount() + " Proveedor(es)");
    }
    
    
         
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnroregistros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstproveedores = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtproveedor = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnroregistros.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lblnroregistros.setText("0 Proveedores");
        lblnroregistros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblnroregistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });
        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyReleased(evt);
            }
        });

        tblstproveedores.setAutoCreateRowSorter(true);
        tblstproveedores.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tblstproveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblstproveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstproveedoresMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblstproveedoresMouseReleased(evt);
            }
        });
        tblstproveedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblstproveedoresKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblstproveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 690, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel4.setText("RUC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        txtproveedor.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproveedorActionPerformed(evt);
            }
        });
        txtproveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtproveedorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtproveedorKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtproveedorKeyReleased(evt);
            }
        });
        jPanel1.add(txtproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 530, -1));

        btnsalir.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnsalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 70, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel5.setText("Proveedor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        txtruc.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrucKeyTyped(evt);
            }
        });
        jPanel1.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 690, 80));

        jPanel2.setBackground(new java.awt.Color(255, 0, 15));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECCIONAR PROVEEDOR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblstproveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstproveedoresMouseClicked

    }//GEN-LAST:event_tblstproveedoresMouseClicked

    private void tblstproveedoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblstproveedoresKeyReleased
//        if (evt.getKeyCode() == KeyEvent.VK_UP) {
//            int fila = tblstproveedores.getSelectedRow();
//            seleccionarfila(fila);
//        }
//        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
//            int fila = tblstproveedores.getSelectedRow();
//            seleccionarfila(fila);
//        }
    }//GEN-LAST:event_tblstproveedoresKeyReleased

    private void tblstproveedoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstproveedoresMouseReleased
        int fila2=tblstproveedores.getSelectedRow();
            if(fila==fila2 && otrofrm==0){
                    
                    SesionUsuario.txtrucpro.setText(tblstproveedores.getValueAt(fila2, 0).toString());
                    SesionUsuario.txtrazonsocial.setText(tblstproveedores.getValueAt(fila2, 2).toString());
                    LAgenteRetenedores la=new LAgenteRetenedores();
                    int esagente= la.VerificarAgente(tblstproveedores.getValueAt(fila2, 0).toString());
                    if(esagente>0){
                        SesionUsuario.rbtretencion.setEnabled(false);
                        //SesionUsuario.rbtdetraccion.setEnabled(false);
                        SesionUsuario.rbtninguno.setSelected(true);
                    }else{
                        SesionUsuario.rbtretencion.setEnabled(true);
                        //SesionUsuario.rbtdetraccion.setEnabled(true);
                        SesionUsuario.rbtninguno.setSelected(true);
                    }
                    this.dispose();
            }else{
                fila=fila2;
            }
            if(fila==fila2 && otrofrm==1){
//                       if(SesionUsuario.txtrucpro != null && otrofrm==1){
                    SesionUsuario.txtrazonsocial.setText(tblstproveedores.getValueAt(fila2, 2).toString());
                    this.dispose();
                       }else{
                      
                fila=fila2;         
            }
    }//GEN-LAST:event_tblstproveedoresMouseReleased

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void jScrollPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyReleased
           if (evt.getKeyCode() == KeyEvent.VK_UP) {
            int fila = tblstproveedores.getSelectedRow();
//            seleccionarfila(fila);
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            int fila = tblstproveedores.getSelectedRow();
//            seleccionarfila(fila);
        }
    }//GEN-LAST:event_jScrollPane1KeyReleased

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
               int fila = tblstproveedores.getSelectedRow();
             if(fila>=0){

//            seleccionarfila(fila);
        
        }
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void txtproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproveedorActionPerformed
        
         
    }//GEN-LAST:event_txtproveedorActionPerformed

    private void txtproveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproveedorKeyTyped
       opc=1;   
        if(txtproveedor.getText().trim().length()>0){
        LComprobante lo = new LComprobante();
            lstproveedor = lo.SeleccionarProveedor(txtproveedor.getText());
            System.out.println(lstproveedor.size());
            if (lstproveedor.size() > 0) {
                listaproveedor();
            }else{
                listaproveedor();
            }   
        }else{
            LComprobante lo = new LComprobante();
            lstproveedor = lo.SeleccionarProveedor("");
            System.out.println(lstproveedor.size());
            if (lstproveedor.size() > 0) {
                listaproveedor();
            }else{
                listaproveedor();
            }   
        }
    }//GEN-LAST:event_txtproveedorKeyTyped

    private void txtproveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproveedorKeyPressed

    }//GEN-LAST:event_txtproveedorKeyPressed

    private void txtproveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproveedorKeyReleased
    
    }//GEN-LAST:event_txtproveedorKeyReleased

    private void txtrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyTyped
        // TODO add your handling code here:
        opc=1;   
        if(txtruc.getText().length()>10){
            evt.consume();
        }
        opc=1;   
        if(txtruc.getText().trim().length()>0){
        LComprobante lo = new LComprobante();
            lstproveedor = lo.SeleccionarProveedorxRuc(txtruc.getText());
            if (lstproveedor.size() > 0) {
                listaproveedor();
            }else{
                listaproveedor();
            }   
        }else{
            LComprobante lo = new LComprobante();
            lstproveedor = lo.SeleccionarProveedor("");
            if (lstproveedor.size() > 0) {
                listaproveedor();
            }else{
                listaproveedor();
            }   
        }
    }//GEN-LAST:event_txtrucKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblnroregistros;
    private javax.swing.JTable tblstproveedores;
    private javax.swing.JTextField txtproveedor;
    private javax.swing.JTextField txtruc;
    // End of variables declaration//GEN-END:variables
}
