/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_ProgPago;

import Capa_Panel.Retencion.FrmExportarGP;
import Capa_Panel.Retencion.InterFrmEmitirCompRetencion;
import Capa_Panel.Retencion.InterFrmFormatearEmitir;
import Capa_Panel.Retencion.InterFrmLibroRetencion;
import Capa_Panel.Retencion.InterFrmTXTDetraccion;
import Capa_Panel.Retencion.InterFrmTXTRetencion;
import Capa_Panel.Retencion.frmExportarGPFinal;
import Capa_PrgMantemiento.BuenosConAgeRete;
import Capa_PrgMantemiento.Detraccion;
import Capa_PrgMantemiento.Parametros;
import Capa_PrgMantemiento.Personal;
import Capa_PrgMantemiento.Proveedores1;
import Capa_PrgMantemiento.TipoCambio;
import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author EXPERTYA
 */
public class Menu extends JFrame  {

    /**
     * Creates new form Menu
     */
    public Menu() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1035, 665);
        setIconImage(new ImageIcon(getClass().getResource("/img/Santander.png")).getImage());
        this.setTitle("Sistema Santander 1.0 - Gerencia de Contabilidad / Programación de Pagos");
        fondo();
        jMenuItem5.setVisible(false);
        //jMenu1.setVisible(false);
    }
    
        private void fondo(){
            Icon expertya = new ImageIcon(getClass().getResource("/img/FONDO_PROG.jpg"));
            lbllogo.setIcon(expertya);       
    }
    
    
    
    
    
    
     public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = this.size();
        Dimension jInternalFrameSize = jif.getSize();
        int width = ((desktopSize.width - jInternalFrameSize.width) / 2 );
        int height = ((desktopSize.height - jInternalFrameSize.height) /4);
        jif.setLocation(width, height);
        jif.setVisible(true);
    }
    
     public void centerJIF2(JInternalFrame jif) {
        Dimension desktopSize = this.size();
        Dimension jInternalFrameSize = jif.getSize();
        int width = ((desktopSize.width - jInternalFrameSize.width) / 2 );
        int height = ((desktopSize.height - jInternalFrameSize.height) /2)-40;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        btSalir = new javax.swing.JButton();
        dpane2 = new javax.swing.JDesktopPane();
        lbllogo = new javax.swing.JLabel();
        btSalir1 = new javax.swing.JButton();
        btSalir2 = new javax.swing.JButton();
        btSalir3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnmatenimiento = new javax.swing.JMenu();
        btnparametros = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Proveedores = new javax.swing.JMenuItem();
        Proveedores1 = new javax.swing.JMenuItem();
        TipoCambio = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        ConceptosDetraccion = new javax.swing.JMenuItem();
        BuenosContribuyentes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();
        btnregistros = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        btncomprobantes = new javax.swing.JMenuItem();
        Consulta = new javax.swing.JMenuItem();
        Programacion = new javax.swing.JMenu();
        ProgramadePagos = new javax.swing.JMenuItem();
        mantenimientodepag = new javax.swing.JMenuItem();
        ConsultadePro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Emision = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        comprobanteretencion = new javax.swing.JMenuItem();
        consultacomprobante = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        exportartxtretencion = new javax.swing.JMenuItem();
        exportarlibroretencion = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        detracion = new javax.swing.JMenu();
        exportartxtdetracion = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(1017, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btSalir.setToolTipText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 35, 29));

        dpane2.setBackground(new java.awt.Color(255, 255, 255));

        lbllogo.setForeground(new java.awt.Color(255, 255, 255));
        lbllogo.setText("jLabel1");
        dpane2.add(lbllogo);
        lbllogo.setBounds(0, 0, 1017, 573);

        getContentPane().add(dpane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1017, 573));

        btSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/programacion2.jpg"))); // NOI18N
        btSalir1.setToolTipText("Programación");
        btSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 35, 29));

        btSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apertura.png"))); // NOI18N
        btSalir2.setToolTipText("Importación");
        btSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir2ActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 29));

        btSalir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facturacion.jpg"))); // NOI18N
        btSalir3.setToolTipText("Comprobantes");
        btSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir3ActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 35, 29));

        btnmatenimiento.setText("   Mantenimientos  ");
        btnmatenimiento.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        btnparametros.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnparametros.setText("Parámetros");
        btnparametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparametrosActionPerformed(evt);
            }
        });
        btnmatenimiento.add(btnparametros);
        btnmatenimiento.add(jSeparator3);

        Proveedores.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        Proveedores.setText("Proveedores");
        Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresActionPerformed(evt);
            }
        });
        btnmatenimiento.add(Proveedores);

        Proveedores1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        Proveedores1.setText("Personal");
        Proveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proveedores1ActionPerformed(evt);
            }
        });
        btnmatenimiento.add(Proveedores1);

        TipoCambio.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        TipoCambio.setText("Tipo de Cambio");
        TipoCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCambioActionPerformed(evt);
            }
        });
        btnmatenimiento.add(TipoCambio);
        btnmatenimiento.add(jSeparator5);

        ConceptosDetraccion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        ConceptosDetraccion.setText("Conceptos Detracción");
        ConceptosDetraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConceptosDetraccionActionPerformed(evt);
            }
        });
        btnmatenimiento.add(ConceptosDetraccion);

        BuenosContribuyentes.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        BuenosContribuyentes.setText("Buenos Cont y Agente Retenedores ");
        BuenosContribuyentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuenosContribuyentesActionPerformed(evt);
            }
        });
        btnmatenimiento.add(BuenosContribuyentes);
        btnmatenimiento.add(jSeparator2);

        Salir.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        btnmatenimiento.add(Salir);

        jMenuBar1.add(btnmatenimiento);

        btnregistros.setText("   Registros");
        btnregistros.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnregistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrosActionPerformed(evt);
            }
        });

        jMenuItem7.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuItem7.setText("Importación");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        btnregistros.add(jMenuItem7);

        btncomprobantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        btncomprobantes.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btncomprobantes.setText("Comprobantes");
        btncomprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprobantesActionPerformed(evt);
            }
        });
        btnregistros.add(btncomprobantes);

        Consulta.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        Consulta.setText("Consulta Comprobantes");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });
        btnregistros.add(Consulta);

        jMenuBar1.add(btnregistros);

        Programacion.setText("   Programación");
        Programacion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        ProgramadePagos.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        ProgramadePagos.setText("Programación de Pagos");
        ProgramadePagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramadePagosActionPerformed(evt);
            }
        });
        Programacion.add(ProgramadePagos);

        mantenimientodepag.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        mantenimientodepag.setText("Mantenimiento de Programación");
        mantenimientodepag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimientodepagActionPerformed(evt);
            }
        });
        Programacion.add(mantenimientodepag);

        ConsultadePro.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        ConsultadePro.setText("Consulta");
        ConsultadePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultadeProActionPerformed(evt);
            }
        });
        Programacion.add(ConsultadePro);

        jMenuBar1.add(Programacion);

        jMenu2.setText("   Data Banco");
        jMenu2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuItem4.setText("Exportar TXT");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuItem5.setText("Importar XLS");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuItem6.setText("Consulta");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        Emision.setText("   Emision");
        Emision.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        jMenu1.setText("Retención");
        jMenu1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        comprobanteretencion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        comprobanteretencion.setText("Comprobante de Retención");
        comprobanteretencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobanteretencionActionPerformed(evt);
            }
        });
        jMenu1.add(comprobanteretencion);

        consultacomprobante.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        consultacomprobante.setText("Consulta de Comprobantes");
        consultacomprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultacomprobanteActionPerformed(evt);
            }
        });
        jMenu1.add(consultacomprobante);
        jMenu1.add(jSeparator12);

        exportartxtretencion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        exportartxtretencion.setText("Exportar TXT - SUNAT");
        exportartxtretencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportartxtretencionActionPerformed(evt);
            }
        });
        jMenu1.add(exportartxtretencion);

        exportarlibroretencion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        exportarlibroretencion.setText("Exportar Libro de Retención");
        exportarlibroretencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarlibroretencionActionPerformed(evt);
            }
        });
        jMenu1.add(exportarlibroretencion);

        Emision.add(jMenu1);
        Emision.add(jSeparator10);

        detracion.setText("Detración");
        detracion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        exportartxtdetracion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        exportartxtdetracion.setText("Exportar TXT - BN");
        exportartxtdetracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportartxtdetracionActionPerformed(evt);
            }
        });
        detracion.add(exportartxtdetracion);

        Emision.add(detracion);
        Emision.add(jSeparator11);

        jMenuItem9.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuItem9.setText("Exportar a GP");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Emision.add(jMenuItem9);

        jMenuBar1.add(Emision);

        jMenu3.setText("Salir");
        jMenu3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnparametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparametrosActionPerformed
         Parametros para = new Parametros();
          dpane2.add(para);
        centerJIF2(para);
        para.setVisible(true);
    }//GEN-LAST:event_btnparametrosActionPerformed

    private void ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresActionPerformed
        Proveedores1 pro = new Proveedores1();
        dpane2.add(pro);
        centerJIF2(pro);
        pro.setVisible(true);
    }//GEN-LAST:event_ProveedoresActionPerformed

    private void TipoCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCambioActionPerformed
        TipoCambio tc = new TipoCambio();
        dpane2.add(tc);
        centerJIF2(tc);
        tc.setVisible(true);
    }//GEN-LAST:event_TipoCambioActionPerformed

    private void ConceptosDetraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConceptosDetraccionActionPerformed
        Detraccion detra = new Detraccion();
        dpane2.add(detra);
        centerJIF2(detra);
        detra.setVisible(true);
    }//GEN-LAST:event_ConceptosDetraccionActionPerformed

    private void BuenosContribuyentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuenosContribuyentesActionPerformed
            BuenosConAgeRete BC = new BuenosConAgeRete();
            dpane2.add(BC);
            centerJIF2(BC);
            BC.setVisible(true);
    }//GEN-LAST:event_BuenosContribuyentesActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void btncomprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprobantesActionPerformed
        RegistroDeComprobantes registro=new RegistroDeComprobantes();
        dpane2.add(registro);
        centerJIF(registro);
        registro.setVisible(true);
    }//GEN-LAST:event_btncomprobantesActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
        ConsultaCompro prue5 = new ConsultaCompro();
        dpane2.add(prue5);
        centerJIF(prue5);
        prue5.setVisible(true);
    }//GEN-LAST:event_ConsultaActionPerformed

    private void ProgramadePagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramadePagosActionPerformed
        ProgramacionPagos prue3=new ProgramacionPagos();
        dpane2.add(prue3);
        centerJIF(prue3);
        prue3.setVisible(true);
    }//GEN-LAST:event_ProgramadePagosActionPerformed

    private void mantenimientodepagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimientodepagActionPerformed
        MantenimientoProgramación prue6 = new MantenimientoProgramación();
        dpane2.add(prue6);
        centerJIF2(prue6);
        prue6.setVisible(true);
    }//GEN-LAST:event_mantenimientodepagActionPerformed

    private void ConsultadeProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultadeProActionPerformed
        ConsultaProgramacion prue4=new ConsultaProgramacion();
        dpane2.add(prue4);
        centerJIF(prue4);
        prue4.setVisible(true);
    }//GEN-LAST:event_ConsultadeProActionPerformed

    private void exportartxtretencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportartxtretencionActionPerformed
        // TODO add your handling code here:
        InterFrmTXTRetencion txtret=new InterFrmTXTRetencion();
        dpane2.add(txtret);
        centerJIF2(txtret);
        txtret.setVisible(true);
    }//GEN-LAST:event_exportartxtretencionActionPerformed

    private void btnregistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrosActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnregistrosActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void comprobanteretencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobanteretencionActionPerformed
        // TODO add your handling code here:
        InterFrmEmitirCompRetencion emitir=new InterFrmEmitirCompRetencion();
        dpane2.add(emitir);
        centerJIF2(emitir);
        emitir.setVisible(true);
    }//GEN-LAST:event_comprobanteretencionActionPerformed

    private void Proveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proveedores1ActionPerformed
        // TODO add your handling code here:
        Personal pers=new Personal();
        dpane2.add(pers);
        centerJIF2(pers);
        pers.setVisible(true);
    }//GEN-LAST:event_Proveedores1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ImportarComprobantes imp=new ImportarComprobantes();
        dpane2.add(imp);
        centerJIF2(imp);
        imp.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Exportartxt exp=new Exportartxt();
        dpane2.add(exp);
        centerJIF2(exp);
        exp.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ImportarXlsBanco imp=new ImportarXlsBanco();
        dpane2.add(imp);
        centerJIF2(imp);
        imp.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void consultacomprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultacomprobanteActionPerformed
        // TODO add your handling code here:
        InterFrmFormatearEmitir interfrm=new InterFrmFormatearEmitir();
        dpane2.add(interfrm);
        centerJIF(interfrm);
        interfrm.setVisible(true);
    }//GEN-LAST:event_consultacomprobanteActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Consultatxt cons=new Consultatxt();
        dpane2.add(cons);
        centerJIF2(cons);
        cons.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void exportartxtdetracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportartxtdetracionActionPerformed
        // TODO add your handling code here:
        InterFrmTXTDetraccion inter=new InterFrmTXTDetraccion();
        dpane2.add(inter);
        centerJIF2(inter);
        inter.setVisible(true);
    }//GEN-LAST:event_exportartxtdetracionActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        frmExportarGPFinal frmexpgp=new frmExportarGPFinal();
        dpane2.add(frmexpgp);
        centerJIF2(frmexpgp);
        frmexpgp.setVisible(true);
        //frmexpgp.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void exportarlibroretencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarlibroretencionActionPerformed
        // TODO add your handling code here:
        InterFrmLibroRetencion inter=new InterFrmLibroRetencion();
        dpane2.add(inter);
        centerJIF2(inter);
        inter.setVisible(true);
                
    }//GEN-LAST:event_exportarlibroretencionActionPerformed

    private void btSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir1ActionPerformed
        // TODO add your handling code here:
        ProgramacionPagos prue3=new ProgramacionPagos();
        dpane2.add(prue3);
        centerJIF(prue3);
        prue3.setVisible(true);
    }//GEN-LAST:event_btSalir1ActionPerformed

    private void btSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir2ActionPerformed
        // TODO add your handling code here:
        ImportarComprobantes imp=new ImportarComprobantes();
        dpane2.add(imp);
        centerJIF2(imp);
        imp.setVisible(true);
    }//GEN-LAST:event_btSalir2ActionPerformed

    private void btSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir3ActionPerformed
        // TODO add your handling code here:
        RegistroDeComprobantes registro=new RegistroDeComprobantes();
        dpane2.add(registro);
        centerJIF(registro);
        registro.setVisible(true);
    }//GEN-LAST:event_btSalir3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuenosContribuyentes;
    private javax.swing.JMenuItem ConceptosDetraccion;
    private javax.swing.JMenuItem Consulta;
    private javax.swing.JMenuItem ConsultadePro;
    private javax.swing.JMenu Emision;
    private javax.swing.JMenu Programacion;
    private javax.swing.JMenuItem ProgramadePagos;
    private javax.swing.JMenuItem Proveedores;
    private javax.swing.JMenuItem Proveedores1;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem TipoCambio;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btSalir1;
    private javax.swing.JButton btSalir2;
    private javax.swing.JButton btSalir3;
    private javax.swing.JMenuItem btncomprobantes;
    private javax.swing.JMenu btnmatenimiento;
    private javax.swing.JMenuItem btnparametros;
    private javax.swing.JMenu btnregistros;
    private javax.swing.JMenuItem comprobanteretencion;
    private javax.swing.JMenuItem consultacomprobante;
    private javax.swing.JMenu detracion;
    public static javax.swing.JDesktopPane dpane2;
    private javax.swing.JMenuItem exportarlibroretencion;
    private javax.swing.JMenuItem exportartxtdetracion;
    private javax.swing.JMenuItem exportartxtretencion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JMenuItem mantenimientodepag;
    // End of variables declaration//GEN-END:variables
}
