/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_ProgPago;

import Capa_Entidades.EComprobante;
import Capa_Entidades.EDetraccion;
import Capa_Logica.LComprobante;
import Capa_Logica.LProgPagosCabecera;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXPERTYA
 */
public class ProgramacionSinRetDet extends javax.swing.JInternalFrame {
    ArrayList<EComprobante> lstdetalle =new ArrayList<>();
    ArrayList<EDetraccion> lisdetra = new ArrayList<>(); 
    String titulos3[] = {"CodProg", "CodCompr", "TipoComprobante", "NumComp", "Fecha", "DocProv", "Glosa", "CompSujeto",
        "FormaPago", "MontoSoles", "MontoDolares", "Estado", "Banco", "Moneda", "CtaBancaria"};
    DefaultTableModel modTbdatos3 = new DefaultTableModel(titulos3, 0);
    int codprog=0;
    String moneda="";
    double retdet=0.0;
    /**
     * Creates new form ProgramacionSinRetDet
     */
    public ProgramacionSinRetDet() {
        initComponents();
        this.setTitle("Aplicar Retención/Detracción");
        setFrameIcon(new ImageIcon(getClass().getResource("/img/Santander.png")));
        rbtreten.setSelected(true);
        llenaConceptoDetra();
        cbodetraccion.setSelectedIndex(0);
        cbodetraccion.setEnabled(false);
        tblstdetalle.setModel(modTbdatos3);
    }

    
    public void listadetalle(ArrayList<EComprobante> lstcompro) {
        lstdetalle=lstcompro;
        modTbdatos3.setRowCount(0);
        if (lstdetalle.size() > 0) {
            for (int i = 0; i < lstdetalle.size(); i++) {
                Object nuevafila[] = new Object[15];
                nuevafila[0] = lstdetalle.get(i).getCodProgramacion();
                nuevafila[1] = lstdetalle.get(i).getCodComprobante();
                nuevafila[2] = lstdetalle.get(i).getTipoComprobante();
                nuevafila[3] = lstdetalle.get(i).getNumComprobante();
                nuevafila[4] = lstdetalle.get(i).getFechaComprobante();
                nuevafila[5] = lstdetalle.get(i).getDocProveedor();
                nuevafila[6] = lstdetalle.get(i).getGlosaComprante();
                nuevafila[7] = lstdetalle.get(i).getComprobanteSujeto();
                nuevafila[8] = lstdetalle.get(i).getFormaPago();
                nuevafila[9] = lstdetalle.get(i).getMontoPagar();
                nuevafila[10] = lstdetalle.get(i).getMontoPagarDOL();
                nuevafila[11] = lstdetalle.get(i).getEstado();
                nuevafila[12] = lstdetalle.get(i).getUsuModi();
                nuevafila[13] = lstdetalle.get(i).getNomMoneda();
                nuevafila[14] = lstdetalle.get(i).getCuentasoles();
                modTbdatos3.addRow(nuevafila);
            }
        }
        tblstdetalle.setModel(modTbdatos3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgretdet = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtreten = new javax.swing.JRadioButton();
        rbtdetracc = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cbodetraccion = new javax.swing.JComboBox();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstdetalle = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel2.setBackground(new java.awt.Color(255, 0, 15));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLICAR RETENCIÓN/DETRACCIÓN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        rbtreten.setBackground(new java.awt.Color(255, 255, 255));
        bgretdet.add(rbtreten);
        rbtreten.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbtreten.setText("Retención");
        rbtreten.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtretenItemStateChanged(evt);
            }
        });

        rbtdetracc.setBackground(new java.awt.Color(255, 255, 255));
        bgretdet.add(rbtdetracc);
        rbtdetracc.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbtdetracc.setText("Detracción");
        rbtdetracc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtdetraccItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Aplicar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N

        cbodetraccion.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        btnguardar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        tblstdetalle.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tblstdetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblstdetalle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtdetracc)
                            .addComponent(rbtreten))))
                .addGap(50, 50, 50)
                .addComponent(cbodetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(rbtdetracc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbtreten))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cbodetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validar(){
        int val = 0;
        if (rbtreten.isSelected()) {
            val = 1;
        }
        if (rbtdetracc.isSelected()) {
            if (cbodetraccion.getSelectedIndex() > 0) {
                val = 1;
            } else {
                JOptionPane.showMessageDialog(this, "Seleccion Concepto de Detracción.");
            }
        }
        if (val == 1) {
            return true;
        } else {
            return false;
        }
    }
    
    private void setearretodet(){
        if(lstdetalle.size()>0){
            for (int i = 0; i < lstdetalle.size(); i++) {
                double montoret=0.00;
                montoret=lstdetalle.get(i).getMontoPagar()*retdet;
                lstdetalle.get(i).setMontoPagar(lstdetalle.get(i).getMontoPagar()-montoret);
                lstdetalle.get(i).setMontoRetDet(montoret);
                System.out.println(montoret);
            }
        }
    }
    
    private void setearretodetdolares(){
        if(lstdetalle.size()>0){
            for (int i = 0; i < lstdetalle.size(); i++) {
                double montoret=0.00;
                montoret=lstdetalle.get(i).getMontoPagarDOL()*retdet;
                lstdetalle.get(i).setMontoPagarDOL(lstdetalle.get(i).getMontoPagarDOL()-montoret);
                lstdetalle.get(i).setMontoRetDetDOL(montoret);
                System.out.println(montoret);
            }
        }
    }
    
    private void llenaConceptoDetra() {
        LComprobante limp = new LComprobante();
        lisdetra = limp.listaDetra();
        cbodetraccion.removeAllItems();
        cbodetraccion.addItem("<Seleccione>");
        for (int i = 0; i < lisdetra.size(); i++) {
            cbodetraccion.addItem((lisdetra.get(i).getPorcentajeDetra() * 100) + "% - " + lisdetra.get(i).getTipoDetra());
        }
    }
    
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if(validar()){
            String rd="";
             if(rbtreten.isSelected()){
                 LComprobante lc=new LComprobante();
                 retdet=lc.porcentajeretencion("0");
                 System.out.println(retdet);
                 rd="RETENCION ";
             }
             if(rbtdetracc.isSelected()){
                 retdet=lisdetra.get(cbodetraccion.getSelectedIndex()-1).getPorcentajeDetra();
                 rd="DETRACCION ";
             }
             if(moneda.equalsIgnoreCase("DOLARES")){
                 setearretodetdolares();
             }
             if (JOptionPane.showConfirmDialog(this, "Se va aplicar "+rd+"a todos los comprobantes en lista. ¿Desea Continuar?", "Confirmar", JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_OPTION)) {
                 setearretodet();
                 int count=0;
                 LProgPagosCabecera lp=new LProgPagosCabecera();
                 for (int i = 0; i < lstdetalle.size(); i++) {
                     lstdetalle.get(i).setComprobanteSujeto(rd);
                     if(lp.ActualizarRetDet(lstdetalle.get(i))){
                         count=count+1;
                     }
                 }
                 if (count == lstdetalle.size()) {
                     JOptionPane.showMessageDialog(this, "Se APLICO correctamente " + rd + " a los Comprobantes.");
                     this.dispose();
                 } else {
                     JOptionPane.showMessageDialog(this, "Error de tipo de Dato y/o Conexión de BD.");
                 }
             }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void rbtdetraccItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtdetraccItemStateChanged
        // TODO add your handling code here:
        if(rbtdetracc.isSelected()){
            cbodetraccion.setEnabled(true);
            cbodetraccion.setSelectedIndex(0);
        }
    }//GEN-LAST:event_rbtdetraccItemStateChanged

    private void rbtretenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtretenItemStateChanged
        // TODO add your handling code here:
        if (rbtreten.isSelected()) {
            cbodetraccion.setEnabled(false);
//            cbodetraccion.setSelectedIndex(0);
        }
    }//GEN-LAST:event_rbtretenItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgretdet;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox cbodetraccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtdetracc;
    private javax.swing.JRadioButton rbtreten;
    private javax.swing.JTable tblstdetalle;
    // End of variables declaration//GEN-END:variables
}
