/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Panel.Exportar;

import Capa_Entidades.EDataFormatCompras;
import Capa_Entidades.EDataFormatVentas;
import Capa_Entidades.EPeriodo;
import Capa_Logica.LImportar;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author EXPERTYA
 */
public class FrmExportarLFormatear extends javax.swing.JFrame {

    ArrayList<EPeriodo> lstperiodo = new ArrayList<>();
    
    /**
     * Creates new form FrmExportar
     */
    public FrmExportarLFormatear() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/Santander.png")).getImage());
        this.setTitle("MÓDULO DE EXPORTAR");
        chkcompras.setSelected(true);
        llenarperiodo();
    }

    private void llenarperiodo() {
        LImportar limp = new LImportar();
        if(chkcompras.isSelected()){
            lstperiodo = limp.ListaPeriodoCompra();
        }else{
            lstperiodo = limp.ListaPeriodoVenta();
        }
        cboperiodo.removeAllItems();
        cboperiodo.addItem("<Seleccione>");
        for (int i = 0; i < lstperiodo.size(); i++) {
            cboperiodo.addItem(lstperiodo.get(i).getMesChar() + " - " + lstperiodo.get(i).getAño());
        }
    }
    
    public void exportaciondeafuera(String mov, String periodo){
        if(mov.equalsIgnoreCase("COMPRAS")){
            chkcompras.setSelected(true);
            cboperiodo.setSelectedItem(periodo);
        }else{
            chkventas.setSelected(true);
            cboperiodo.setSelectedItem(periodo);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgfiltro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboperiodo = new javax.swing.JComboBox();
        chkcompras = new javax.swing.JCheckBox();
        chkventas = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtruta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXPORTAR REGISTROS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 18));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel2.setText("Ruta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        cboperiodo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        cboperiodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>" }));
        jPanel1.add(cboperiodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, -1));

        chkcompras.setBackground(new java.awt.Color(255, 255, 255));
        bgfiltro.add(chkcompras);
        chkcompras.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        chkcompras.setText("Compras");
        chkcompras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkcomprasStateChanged(evt);
            }
        });
        chkcompras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkcomprasItemStateChanged(evt);
            }
        });
        jPanel1.add(chkcompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 20));

        chkventas.setBackground(new java.awt.Color(255, 255, 255));
        bgfiltro.add(chkventas);
        chkventas.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        chkventas.setText("Ventas");
        chkventas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkventasStateChanged(evt);
            }
        });
        chkventas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkventasItemStateChanged(evt);
            }
        });
        jPanel1.add(chkventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 60, 20));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("Período");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        txtruta.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel1.add(txtruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 89, -1, 22));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/export.png"))); // NOI18N
        jButton2.setText("Exportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkventasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkventasStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkventasStateChanged

    private void chkcomprasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkcomprasStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_chkcomprasStateChanged

    private void chkcomprasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkcomprasItemStateChanged
        // TODO add your handling code here:
        llenarperiodo();
    }//GEN-LAST:event_chkcomprasItemStateChanged

    private void chkventasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkventasItemStateChanged
        // TODO add your handling code here:
        llenarperiodo();
    }//GEN-LAST:event_chkventasItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser jF1 = new javax.swing.JFileChooser();
        String ruta = "";
        try {
                jF1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                if (jF1.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                    ruta = jF1.getSelectedFile().getAbsolutePath();
                    String nombrearchivo="";
                    if(chkcompras.isSelected()){
                    nombrearchivo="LE20550226589"+lstperiodo.get(cboperiodo.getSelectedIndex()-1).getAño()+lstperiodo.get(cboperiodo.getSelectedIndex()-1).getMesChar()+
                            "00080100001111";    
                    }else{
                    nombrearchivo="LE20550226589"+lstperiodo.get(cboperiodo.getSelectedIndex()-1).getAño()+lstperiodo.get(cboperiodo.getSelectedIndex()-1).getMesChar()+
                          "00140100001111";
                    }
                txtruta.setText(ruta +"\\" +nombrearchivo+".txt");
            }
        } catch (Exception ex) {
            ex.getMessage();
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtruta.getText().trim().length() > 0) {
            String nombrearchivo = "";
            int ultimoslash = txtruta.getText().trim().lastIndexOf("\\") + 1;
            if(ultimoslash>0){
                nombrearchivo = txtruta.getText().trim().substring(ultimoslash, txtruta.getText().trim().length());
                File archivo=new File(txtruta.getText().trim());
                try {
                    LImportar lim=new LImportar();
                    FileWriter escribir=new FileWriter(archivo,true);
                    if(chkcompras.isSelected()){
                        ArrayList<EDataFormatCompras> listcompras=new ArrayList<>();
                        listcompras=lim.ListaDataFormatCompras(lstperiodo.get(cboperiodo.getSelectedIndex()-1).getCodigo());
                        if(listcompras.size()>0){
                            for (int i = 0; i < listcompras.size(); i++) {
                                String filastring=listcompras.get(i).getCampo1().trim() + "|"+
                                        listcompras.get(i).getCampo2().trim() + "|"+
                                        listcompras.get(i).getCampo3().trim() + "|"+                                        
                                        listcompras.get(i).getCampo4().trim() + "|"+
                                        listcompras.get(i).getCampo5().trim() + "|"+
                                        listcompras.get(i).getCampo6().trim() + "|"+
                                        listcompras.get(i).getCampo7().trim() + "|"+
                                        listcompras.get(i).getCampo8().trim() + "|"+
                                        listcompras.get(i).getCampo9().trim() + "|"+
                                        listcompras.get(i).getCampo10().trim() + "|"+
                                        listcompras.get(i).getCampo11().trim() + "|"+
                                        listcompras.get(i).getCampo12().trim() + "|"+
                                        listcompras.get(i).getCampo13().trim() + "|"+
                                        listcompras.get(i).getCampo14().trim() + "|"+
                                        listcompras.get(i).getCampo15().trim() + "|"+
                                        listcompras.get(i).getCampo16().trim() + "|"+
                                        listcompras.get(i).getCampo17().trim() + "|"+
                                        listcompras.get(i).getCampo18().trim() + "|"+
                                        listcompras.get(i).getCampo19().trim() + "|"+
                                        listcompras.get(i).getCampo20().trim() + "|"+
                                        listcompras.get(i).getCampo21().trim() + "|"+
                                        listcompras.get(i).getCampo22().trim() + "|"+
                                        listcompras.get(i).getCampo23().trim() + "|"+
                                        listcompras.get(i).getCampo24().trim() + "|"+
                                        listcompras.get(i).getCampo25().trim() + "|"+
                                        listcompras.get(i).getCampo26().trim() + "|"+
                                        listcompras.get(i).getCampo27().trim() + "|"+
                                        listcompras.get(i).getCampo28().trim() + "|"+
                                        listcompras.get(i).getCampo29().trim() + "|"+
                                        listcompras.get(i).getCampo30().trim() + "|"+
                                        listcompras.get(i).getCampo31().trim() + "|"+
                                        listcompras.get(i).getCampo32().trim() + "|"+
                                        listcompras.get(i).getCampo33().trim() + "|"+
                                        listcompras.get(i).getCampo34().trim() + "|"
                                        + listcompras.get(i).getCampo35().trim() + "|"
                                        + listcompras.get(i).getCampo36().trim() + "|"
                                        + listcompras.get(i).getCampo37().trim() + "|"
                                        + listcompras.get(i).getCampo38().trim() + "|"
                                        + listcompras.get(i).getCampo39().trim() + "||"
                                        //+ listcompras.get(i).getCampo40().trim() + "|"
                                        + listcompras.get(i).getCampo41().trim() + "|";
                                        escribir.write(filastring);
                                        if(i<listcompras.size()-1){
                                        escribir.write("\r\n");    
                                        }
                            }
                            lim.InsertarDataExportCompras(lstperiodo.get(cboperiodo.getSelectedIndex()-1).getCodigo(), listcompras.size());
                        }
                    }else{
                        ArrayList<EDataFormatVentas> lstventas=new ArrayList<>();
                        lstventas=lim.ListaDataFormatVentas(lstperiodo.get(cboperiodo.getSelectedIndex()-1).getCodigo());
                        if(lstventas.size()>0){
                            for (int i = 0; i < lstventas.size(); i++) {
                                String filastring = lstventas.get(i).getCampo1().trim() + "|"
                                        + lstventas.get(i).getCampo2().trim() + "|"
                                        + lstventas.get(i).getCampo3().trim() + "|"
                                        + lstventas.get(i).getCampo4().trim() + "|"
                                        + lstventas.get(i).getCampo5().trim() + "|"
                                        + lstventas.get(i).getCampo6().trim() + "|"
                                        + lstventas.get(i).getCampo7().trim() + "|"
                                        + lstventas.get(i).getCampo8().trim() + "|"
                                        + lstventas.get(i).getCampo9().trim() + "|"
                                        + lstventas.get(i).getCampo10().trim() + "|"
                                        + lstventas.get(i).getCampo11().trim() + "|"
                                        + lstventas.get(i).getCampo12().trim() + "|"
                                        + lstventas.get(i).getCampo13().trim() + "|"
                                        + lstventas.get(i).getCampo14().trim() + "|"
                                        + lstventas.get(i).getCampo15().trim() + "|"
                                        + lstventas.get(i).getCampo16().trim() + "|"
                                        + lstventas.get(i).getCampo17().trim() + "|"
                                        + lstventas.get(i).getCampo18().trim() + "|"
                                        + lstventas.get(i).getCampo19().trim() + "|"
                                        + lstventas.get(i).getCampo20().trim() + "|"
                                        + lstventas.get(i).getCampo21().trim() + "|"
                                        + lstventas.get(i).getCampo22().trim() + "|"
                                        + lstventas.get(i).getCampo23().trim() + "|"
                                        + lstventas.get(i).getCampo24().trim() + "|"
                                        + lstventas.get(i).getCampo25().trim() + "|"
                                        + lstventas.get(i).getCampo26().trim() + "|"
                                        + lstventas.get(i).getCampo27().trim() + "|"
                                        + lstventas.get(i).getCampo28().trim() + "|"
                                        + lstventas.get(i).getCampo29().trim()+"|";
                                escribir.write(filastring);
                                if(i<lstventas.size()-1){
                                    escribir.write("\r\n");    
                                }
                            }
                            lim.InsertarDataExportVentas(lstperiodo.get(cboperiodo.getSelectedIndex()-1).getCodigo(), lstventas.size());
                        }
                    }
                    escribir.close();
                    JOptionPane.showMessageDialog(this, "Se exportó correctamente el archivo "+nombrearchivo+".");
                    txtruta.setText("");
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                    Logger.getLogger(FrmExportarLFormatear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Ruta Indicada no es válida.");
                txtruta.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione Ruta de Archivo.");
            txtruta.requestFocus();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmExportarLFormatear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmExportarLFormatear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmExportarLFormatear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmExportarLFormatear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmExportarLFormatear().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgfiltro;
    private javax.swing.JComboBox cboperiodo;
    private javax.swing.JCheckBox chkcompras;
    private javax.swing.JCheckBox chkventas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
